### ISSUE TITLE
Basic and CKeditor image problem 

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#275] opened 2015-08-07 17:58 UTC
Hi @svivian @pupi1985 
I have one problem. 
Example: I create question or answer use CKeditor. I upload image for question or answer text. After i use site mobile phone and edit my question or answer. But basic editor deleted image or link my post.
Basic editor deleted image my post.

**Comment by gurjyot** [comment] 2015-08-07 18:39
I actually got what yerbol89 is trying to say. If we edit a question (through a mobile) having an image, then after saying the question, that image disappears. I have faced the same problem. We do not delete the image but still it gets deleted while editing content through mobile.

**Comment by pupi1985** [comment] 2016-11-12 06:31
Not a bug :)

The thing is the CKEditor is not loading on Android. Updating to latest version does not fix the issue either. However, CKEditor claims that it will fully support mobile on version 5 (currently 4.5.11).

On the other hand, it is possible to use force it by removing the version check (which happens by means of the User-Agent). Download and install the latest version of CKEditor. Then edit this line:

https://github.com/q2a/question2answer/blob/4fce0eb2390f56b645dad375d1d81e9f91a97e69/qa-plugin/wysiwyg-editor/qa-wysiwyg-editor.php#L202

And turn it into:
```
"CKEDITOR.env.isCompatible = true; if (qa_ckeditor_".$fieldname." = CKEDITOR.replace(".qa_js($fieldname).", qa_wysiwyg_editor_config)) { " .
```

Note I'm just adding `CKEDITOR.env.isCompatible = true;` in a very dirty and quick way. However, this will force CKEditor to load in unsupported environments. This of course might bring additional issues with CKEditor as it has not been tested in the given devices but it is up to you if you want to run the risk.

I'd close this as a `won't fix`.

PS: Some interesting links: http://ckeditor.com/blog-list and https://ckeditor5.github.io (looks nice and works on mobile!)

**Comment by svivian** [comment] 2017-03-11 21:09
@yerbol89 Can you tell me if the demo on the [CKEditor home page](http://ckeditor.com/) works for you in Android? Or does that show a basic editor too? That's using the latest version (4.6) which will be added to Q2A 1.8.

**Comment by gurjyot** [comment] 2017-03-12 04:16
@svivian I tired Ckeditor on android mobile. And it works there so updating to latest version of ckeditor can help a lot to Q2A.

**Comment by pupi1985** [comment] 2017-03-18 16:33
I can confirm the new version is working fine in Q2A too (just made a rough update of the plugin in Q2A and worked fine). Just bear in mind to clear the browser's cache.

**Closed** 2017-09-04 23:59 UTC
Labels: bug
