### ISSUE TITLE
When select messaging area, other sections be lost

### ISSUE THREAD

**Issue by dmrrmd0606** [q2a/question2answer#489] opened 2017-01-23 10:44 UTC
When user access to own profile page,User see
User Name 	section
My account	section
My favorites	section
Wall			section
Sections on menu, but when user access to Private Message section, other options removed. Just show Inbox and Send items sections. But when access other sections, nothing remove.

**Comment by svivian** [comment] 2017-01-23 14:00
PMs are their own section with sub-pages (inbox/sent) so that was the rationale behind it. But maybe it wasn't the best design. I think a few people would have preferred the PM page to be a list of conversations rather than just inbox and sent items.

**Comment by gurjyot** [comment] 2017-03-19 20:11
Yes @svivian , a list of conversations would have been best. That way we can easily see the conversations with different members without going into inbox and sent (again and again).

**Comment by svivian** [comment] 2017-09-05 13:14
I've moved the Inbox/Sent links into the main page and reverted the menu back to the standard user menu. That solves the main issue; the other concern about the PM structure is a duplicate of #78.

**Closed by svivian** 2017-09-05 13:14 UTC
Labels: refactor
