### ISSUE TITLE
A notes link is rendered unusable by prefixing it with the word "denied:"

### ISSUE THREAD

**Issue by rumpumpel1** [q2a/question2answer#969] opened 2022-10-25 11:59 UTC
After entering a notes link like in a text field (question/answer/comment) and after saving and closing the dialog the link is prepended by the word "denied:" which renders the link unusable. 
A notes link is something like "notes:///xxxxxxxxxxx".  See https://www.hcltechsw.com/notes.
This is NOT an issue of ckeditor. The culprit is q2a/qa-inlude/vendor/htmLawed.php line 340.

**Comment by pupi1985** [comment] 2022-10-25 13:09
So you are marking a post as duplicate of another post and the URL of the original post starts with "notes:///" ?

Please, use the URL of the web page of the original post... https://yoursite.com/12345

**Comment by rumpumpel1** [comment] 2022-10-30 08:31
pupi1985: I did not understand your comment.

**Comment by svivian** [comment] 2023-07-06 12:51
There are a million different schemes and we can't support them all. However you can add your own by overriding the `qa_sanitize_html` function using [function overrides](https://docs.question2answer.org/plugins/overrides/). Copy the existing function and change the 'schemes' key to something like

    'schemes' => 'notes, href: aim, feed, file, ftp, gopher, http, https, irc, mailto, news, nntp, sftp, ssh, telnet; *:file, http, https; style: !; classid:clsid',

**Closed by svivian** 2023-07-06 12:51 UTC
