### ISSUE TITLE
Cannot search in thai language

### ISSUE THREAD

**Issue by d0L0b** [q2a/question2answer#582] opened 2017-12-27 04:54 UTC
I post ask question and content in Thai language then search but cannot found anything. another language such as English , Japan it OK.

**Comment by svivian** [comment] 2017-12-28 11:58
Do you have an example website where the problem is occurring? What exactly are you putting in the search box, and what exactly are you expecting it to match?

**Comment by d0L0b** [comment] 2018-01-01 07:06
The problem is cannot detect content in Thai language 
in search box just put same word from content posted in Thai such as
http://demo.question2answer.org/search?q=ภาษาไทย

Thank you for your answer

"HAPPY NEW YEAR 2018"

**Comment by svivian** [comment] 2018-01-01 12:23
You'll have to be more specific, I made a question with your example search query and it works fine:

![q2a-thai](https://user-images.githubusercontent.com/207887/34467610-74899e9c-eeee-11e7-9c5a-ddf373fd54e6.jpg)

**Comment by d0L0b** [comment] 2018-01-01 17:12
เว็บไซต์ตัวอย่างเพื่อทดสอบคำค้นหาสำหรับภาษาไทยเมื่อผู้ใช้ต้องการค้นหาโดยใช้คำค้นหาสำหรับการพิมพ์ภาษาไทยใดๆก็ตามหรืออะไรก็ตามในช่องค้นหาและผู้ใช้คาดหวังว่าจะตรงกับคำค้นหาภาษาไทยที่ต้องการ

ตัวอย่างคำที่ต้องการเช่นคำว่าภาษาไทย ภาษาอังกฤษ ภาษาญี่ปุ่น

From the above sample, If we search ภาษาไทย it cannot found. but if search ภาษาอังกฤษ or ภาษาญี่ปุ่น it found. Seem like search find only a single word (the word after space/tap space), see sample under red line as file.

![image](https://user-images.githubusercontent.com/34876801/34469430-4088f1de-ef51-11e7-9dbe-1c4847d31cc4.png)

**Comment by svivian** [comment] 2018-01-02 12:51
OK I guess Thai is similar to the Chinese/Japanese languages where you don't have spaces between words.

We have a system in place for dealing with CJK characters - see the bottom of `qa-include/util/string.php`. The `QA_PREG_CJK_IDEOGRAPHS_UTF8` constant is used to match CJK characters and split them when searching/indexing. So that will need to be modified to handle Thai characters too. I'll look into that when I can.

**Comment by d0L0b** [comment] 2018-01-02 17:35
Thank you for your reply. if you have any update I'll be happy to hear from you.
Take care and have a nice day.

**Comment by svivian** [comment] 2018-01-02 20:15
No need to close this, I’ll keep it open as a reminder until the issue is fixed :)

**Comment by d0L0b** [comment] 2018-01-03 06:03
You are so kind and very nice. I'll keep my eye on for your reply :)
Have a lovely day :)

**Comment by svivian** [comment] 2018-12-11 22:19
Sorry for the delay, I finally got around to fixing this (latest code in bugfix branch). Will be part of Q2A 1.8.2.

**Closed by svivian** 2018-12-11 22:19 UTC
Labels: bug
