### ISSUE TITLE
Provide comments list per user - next to answers and questions list

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#335] opened 2015-12-14 11:42 UTC
I regularly run into the problem that I am searching for one of my comments on http://www.question2answer.org/qa/

And cannot find it because there is no list of comments. 

A list of comments would help tremendously. The answers list and questions list are good. Only the comments list is missing. 

Thus, I am asking to add it to the core. I tried it myself but was not able to.

@svivian @pupi1985

**Comment by svivian** [comment] 2015-12-31 00:05
Going to close this for now since it's not a bug. But I know several people have requested this before so I will certainly consider it for the future.

**Closed by svivian** 2015-12-31 00:05 UTC

**Comment by q2apro** [comment] 2015-12-31 08:51
Thanks. And yes, I know it is not a bug - but that inconvinient so that I - for the first and last time - considered to post it here ;) Wish you a great party for Happy New Year.

**Comment by q2apro** [comment] 2018-01-28 07:54
I tried to implement it but I ran into some problems. It's 2018, can we get it finally? Would be really awesome!

**Comment by q2apro** [comment] 2019-06-25 11:11
Alright, I finally found the solution. Much easier than I thought because gidgreen already prepared a function for this (!!!)

Steps:

**1. qa-lang-profile.php** 
Add line: `'comments_by_x' => 'Kommentare von ^',`

**2. /pages/user.php**
In the block of `switch (qa_request_part(2)) { ...` add:

	case 'comments':
		qa_set_template('user-comments');
		$qa_content = include QA_INCLUDE_DIR . 'pages/user-comments.php';
		break;

**3. Copy /pages/user-answers.php to /pages/user-comments.php**

**4. Edit /pages/user-comments.php**

Replace all "answers" strings with "comments".

Important: Replace `qa_db_user_recent_a_qs_selectspec($loginuserid, $identifier, qa_opt_if_loaded('page_size_activity'), $start)`
With: `qa_db_user_recent_c_qs_selectspec($loginuserid, $identifier, qa_opt_if_loaded('page_size_activity'), $start)`

Done.

**THIS should go into the core!**

**Comment by arjunsuresh** [comment] 2019-06-25 11:30
@q2apro  Great :) Can you push these changes to Q2A?

**Comment by q2apro** [comment] 2019-06-25 11:34
No. That's why I noted it down. Takes 3 min to edit.

**Comment by arjunsuresh** [comment] 2019-06-26 03:10
Yes, but since the changes are standard they can straight away go to core I feel. I can also push it, if that works.
