### ISSUE TITLE
Take ages to load page if jump from the Plugin page to any other

### ISSUE THREAD

**Issue by q2amarket** [q2a/question2answer#514] opened 2017-04-06 16:18 UTC
@svivian 
It takes ages to load and sometimes time out occur when jumping from Admin > Plugin page to any other page. 

**Here is the error message**
`Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\qa\qa-include\app\users.php on line 146`

**Comment by svivian** [comment] 2017-04-06 17:13
Only thing I can think of is that if you have a lot of plugins, loading the plugin page does a lot of plugin update checks, maybe that's slowing down your site.

**Comment by q2amarket** [comment] 2017-04-06 17:17
I have only 2 additional plugins and rest are from out of the box

**Comment by svivian** [comment] 2017-04-12 10:57
Can you turn on `QA_DEBUG_PERFORMANCE` in `qa-config.php` and post a screenshot of the timing table from the bottom of the page? That may help diagnose the issue.

**Comment by q2amarket** [comment] 2017-04-14 06:28
Sure, I will do and post it here.

**Comment by svivian** [comment] 2017-07-08 21:45
Closing this as I cannot reproduce and have no further information. If you're able to figure out why this happens then post details and I'll reopen.

**Closed by svivian** 2017-07-08 21:45 UTC
