### ISSUE TITLE
Changing function qa_format_number()?

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#722] opened 2019-01-01 08:33 UTC
For better readability I would like to have (for the /users/ page) the output without decimal. At the moment it is like this:

![image](https://user-images.githubusercontent.com/6764548/50571331-01f4d480-0da8-11e9-8211-f926dcea8d4b.png)

For example: 83,9k should be rounded to 84k.

As the function says:

https://github.com/q2a/question2answer/blob/5a8ec779919b25a3626d93b6e5d63ceeb994353d/qa-include/app/format.php#L2363

The value doesn't get rounded if the number is shortened.

It would be great to have all ... `k` values rounded (all values above 1000 points).

**Comment by svivian** [comment] 2020-05-11 20:50
Closing as duplicate of #781

**Closed by svivian** 2020-05-11 20:50 UTC
