### ISSUE TITLE
Getting issue in Upgrade to question2answer 1.8.0

### ISSUE THREAD

**Issue by GaneshKandu** [q2a/question2answer#604] opened 2018-02-09 12:12 UTC
Hi,

i am Getting issue in Upgrade of question2answer 1.7.5 to 1.8.0

#### Step to Reproduce

- Download new version / unzip, upload and overwrite all the current files except config file
- login to your Admin Control Panel

When trying to Login Getting Error
 
![1](https://user-images.githubusercontent.com/12833130/36027260-6a348cdc-0d92-11e8-946d-fabe4f39f375.png)

![2](https://user-images.githubusercontent.com/12833130/36027061-8f5e3536-0d91-11e8-8de9-8d6bb9ea41d8.png)

#### system

- php 5.3.29
- Browser Mozilla/5.0, Chrome
- mysql 5.6
- server apache 2.4

**Comment by svivian** [comment] 2018-03-01 15:55
Can you try setting `QA_HTML_COMPRESSION` to false in `qa-config.php` and see if that works? We did have a problem with that before but it should be fixed.

**Comment by GaneshKandu** [comment] 2018-03-01 18:10
yes its works with 
```php
define('QA_HTML_COMPRESSION', false);
```

**Comment by svivian** [comment] 2018-03-03 13:57
OK there must still be a problem with this. Were you definitely upgrading to 1.8.0 final, not a beta release?

**Comment by GaneshKandu** [comment] 2018-03-05 04:24
i am trying to upgrade to final question2answer 1.8.0

**Comment by svivian** [comment] 2018-03-06 21:03
Managed to reproduce using PHP 5.3. It doesn't occur on PHP 7. The problem is with the `ob_end_clean();` line in `qa-include/qa-install.php`. Removing that fixes the problem, but that line is required to fix other issues (6355a05, c4e7e7e). So I'm not really sure at the moment how this can be solved.

**Comment by svivian** [comment] 2018-03-06 22:22
Managed to find a solution that works in my tests. Though I wonder if we should just scrap the gzip option, as it's best handled either through PHP's `zlib.output_compression` option or at the server level (e.g. Apache `mod_deflate`).

**Closed by svivian** 2018-03-06 22:22 UTC
