### ISSUE TITLE
Foreign key constraint closedbyid

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#330] opened 2015-11-29 18:13 UTC
I am on v1.7.1, the following problem:

	PHP Question2Answer MySQL query error 1451: Cannot delete or update a parent row: a foreign key constraint fails (`db348277_6`.`qa_posts`, CONSTRAINT `qa_posts_ibfk_4` FOREIGN KEY (`closedbyid`) REFERENCES `qa_posts` (`postid`)) - Query: DELETE FROM qa_posts WHERE postid=290806

The post 290806 was referenced from post 290807. Post 290807 was closed as duplicate to 290806. 

Here should be a check if the postid is not set as closedbyid in qa_posts.

**Comment by svivian** [comment] 2015-12-01 12:37
How were you deleting the post? Through normal Q2A usage? (i.e. hising a post then clicking the delete button)

**Comment by q2apro** [comment] 2015-12-01 14:12
Yes, through the interface frontend.

**Comment by svivian** [comment] 2016-01-02 23:36
Looking into this now and trying to figure out the best solution. In short, when a question is closed as a duplicate, it is linked to that original question, so the original question cannot be deleted.

Two possible solutions:

1. Hide the delete button and prevent questions being deleted when other questions are closed as dupes of it. This is actually what happens for "related questions" - when the original answer is hidden it cannot be deleted.
2. Allow deleting, but change how the dupe questions are closed. So if you want to delete an 'original' question, the duplicate is first changed to be closed for another reason, like generic "duplicate" text.

I think it would also be sensible to have warnings somewhere in this process, or a final confirmation like "Another question is closed as a duplicate of this one. Are you sure you want to delete it?"

Another issue I've noticed it that when we hide an original question the dupe still links to it - i/e/ it says "closed as a duplicate of [question]" but that link goes to a hidden question. Same for related questions. So we should remove those links too.

Thoughts?

**Comment by q2apro** [comment] 2016-01-03 12:59
Well, I am using the merge plugin of NoahY, and modified it. This way I: 
1. close the duplicate question, 
2. then convert it into a comment of the original question

This way the content of the dup is still available. And the good thing, q2a provides all unindexing functions needed to remove the "deleted" question id from tagwords etc.

**Comment by svivian** [comment] 2016-01-27 21:22
OK took a fair bit of rewriting but finally managed to sort out all the issues from this.

- If question A is closed as a duplicate of question B then B is hidden, the delete button no longer shows.
- No longer errors from "delete hidden questions" recalc script.
- To make it clearer why B can't be deleted, we now show the duplicate questions (as comments) when B is hidden.
- If B is hidden, don't link to it from A.
- Similar changes made for follow-on questions ("ask related question" button).
- A couple other minor bugs fixed along the way!

This will be part of 1.8.

**Closed by svivian** 2016-01-27 21:22 UTC
Labels: bug

**Comment by q2apro** [comment] 2016-01-30 09:21
Well, obviously you went a different way than the plugin does. 

> If question A is closed as a duplicate of question B then B is hidden, the delete button no longer shows.
Why is B hidden if B is the original?! 

> To make it clearer why B can't be deleted, we now show the duplicate questions (as comments)
That one sounds good.

As said, I am quite happy with the plugin. It merges the question A (dup) to B (org) and I extended it with a conversion of A into a comment to B. 

I really hope that your changes will not affect the usage of this nice plugin.

**Comment by svivian** [comment] 2016-01-30 11:51
Sorry I'm confused now...

> Why is B hidden if B is the original?!

That's the bug you reported, isn't it? "Post 290807 was closed as duplicate to 290806" and you were deleting 290806 (which requires it to be hidden first).

> I really hope that your changes will not affect the usage of this nice plugin.

Based on what you say the plugin does, it shouldn't affect anything. The only thing is Q2A also adds 'comments' listing the duplicates, but only when the question is hidden.

**Comment by q2apro** [comment] 2016-01-30 12:45
Ah, that sentence was ambiguous. I thought this is your change: "If question A is closed as a duplicate of question B **then** [follows that] B is hidden". I did not realize that you just describing the user action. My fault.

For the latter: I hope so! :)

PS: The top 2 left on my recent list: 
- comment list per user (I wanted to do it myself but wasn't able to create it from the existing code)
- sorting open questions by upvotes (code in the q2a forum, just a couple of lines)

Thanks!
Kai
