### ISSUE TITLE
Query in qa_db_user_rank_selectspec() not working with MySQL 8.0

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#892] opened 2021-04-02 06:28 UTC
This query does not work anymore with mysql version 8.0:

    SELECT 1+COUNT(*) AS rank FROM ^userpoints WHERE points>COALESCE((SELECT points FROM ^userpoints WHERE userid=(SELECT userid FROM ^users WHERE handle='rgs.129' LIMIT 1)), 0)

From: `/qa-include/db/selects.php`

```
function qa_db_user_rank_selectspec($identifier, $isuserid = QA_FINAL_EXTERNAL_USERS)
{
	return array(
		'columns' => array('rank' => '1+COUNT(*)'),
		'source' => '^userpoints WHERE points>COALESCE((SELECT points FROM ^userpoints WHERE userid=' . ($isuserid ? '$' : '(SELECT userid FROM ^users WHERE handle=$ LIMIT 1)') . '), 0)',
		'arguments' => array($identifier),
		'arrayvalue' => 'rank',
		'single' => true,
	);
}
```

How to fix that?

**Comment by q2apro** [comment] 2021-04-02 06:35
In general, I think we should not rely on the handle in any case!

The $userid has to be used.

**Comment by q2apro** [comment] 2021-04-02 06:40
Found the problem:

> The word rank is a reserved word in MySql 8.

https://stackoverflow.com/q/54343203/1066234

**Comment by q2apro** [comment] 2021-04-02 06:45
Suggested Fix: Change 'rank' to 'userrank' in:

- `/qa-include/db/selects.php`
- `/qa-include/pages/user-profile.php`

**Comment by svivian** [comment] 2021-04-16 10:09
Which version of Q2A are you using? This issue should have been fixed in v1.8.3. I cannot reproduce in v1.8.5.

**Comment by q2apro** [comment] 2021-04-19 03:51
I haven't updated yet. 

Another fix would be to wrap `rank` into ticks `.

How was ist fixed? I cannot find it here: https://github.com/q2a/question2answer/blob/dev/qa-include/db/selects.php

**Comment by svivian** [comment] 2021-04-19 15:26
Yes backticks are added. The fix is in `qa-db.php`, see here: 8e9c262

**Closed by svivian** 2021-04-19 15:26 UTC
