### ISSUE TITLE
Unusual Blank space between vote box and user avatar in mobile view

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#472] opened 2016-11-28 14:04 UTC
I think this image is enough to show everything.

![and](https://cloud.githubusercontent.com/assets/6462850/20671055/b85b27bc-b5a1-11e6-8e53-8da9ff9c4453.png)

**Comment by svivian** [comment] 2016-11-28 14:43
Is this the SnowFlat theme? I'm not able to reproduce the problem here on either the dev or 1.8 branch.

Do you have a link to a live website showing the problem?

**Comment by gurjyot** [comment] 2016-11-28 14:54
It's happening on main Question2Answer.org/qa.

**Comment by pupi1985** [comment] 2016-11-28 15:54
This is the link: http://www.question2answer.org/qa/55039/new-release-chat-room-extended?show=55040#a55040

Anyway, it looks good for me. What browser and version are you using?

It looks fine for me in:
- Chrome 54.0.2840.100 (64-bit)
- FIrefox ESR 45.5.0

**Comment by svivian** [comment] 2016-11-28 16:47
Thanks, I was looking at the question avatar rather than the answer one. Now fixed.

**Closed by svivian** 2016-11-28 16:47 UTC

**Comment by gurjyot** [comment] 2016-11-28 17:58
Thanks for solving this issue :)
