### ISSUE TITLE
% in title post

### ISSUE THREAD

**Issue by fulldecent** [q2a/question2answer#329] opened 2015-11-23 22:13 UTC
Creating a question with % (like 100%) in the name of the question will cause it to not load.

Please set the Admin / General setting to pretty urls to see this error.

**Comment by amiyasahu** [comment] 2015-11-24 07:40
similar discussion here #303

**Comment by svivian** [comment] 2015-11-27 18:14
What is the exact URL you get? When I make a question with a % I get a URL like this:

    /99/are-question-titles-100%25-encoded

So the % is encoded fine.

**Comment by fulldecent** [comment] 2015-11-29 17:48
Here is a URL that works:
https://heroanswers.org/142

On the site if I search for `i pass on if i am` then click the link in the search result it will load this URL
https://heroanswers.org/142/can-wife-receive-benefits-after-pass-and-100%25-unemployable?show=142#q142

But the latter does not work

**Comment by svivian** [comment] 2015-12-01 12:23
I think this must be a server problem. The % is encoded properly in the URL and it works fine on other Q2A sites. Your server is returning a 404 error for some reason.

Can you try a few things? If you have a test server (e.g. localhost) where you can replicate the issue, do it there. Otherwise you'll have to do it on the live site and remove it afterwards.

Try this inside the `qa_index_set_request` function (`qa-index.php`, line 56)

    echo '';

That will show what Apache thinks the URL is. It's in a comment so it won't show to your visitors - view source and it will be at the top, copy and paste it here.

Also try this in `qa-include/pages/question.php` near the top (e.g. line 40)

    echo '';

Again, view source to see it and copy-paste here. Thanks.

**Comment by fulldecent** [comment] 2015-12-10 23:41
I have tried this on the live site but did not see that line on the output. Not sure what is going on. I will see if there is a small test case I can make.

**Comment by svivian** [comment] 2015-12-28 19:04
Any luck with this? You could try that first code snippet right at the top of `index.php` if it helps, and maybe `var_dump($_SERVER['REQUEST_URI'])` instead.

Are you using `.htaccess` for the URLs? Could you post it here?

**Comment by fulldecent** [comment] 2016-01-07 22:37
For documentation, here is what is broken with the page:

![screen shot 2016-01-07 at 5 33 03 pm](https://cloud.githubusercontent.com/assets/382183/12184680/c2ffac30-b564-11e5-99af-ed4046db1d99.png)

Whereas this works:

![screen shot 2016-01-07 at 5 34 21 pm](https://cloud.githubusercontent.com/assets/382183/12184701/ebb9ae96-b564-11e5-9cae-139afa0c9645.png)

I have fixed the banner by using a full URL including scheme. However, the CSS is still broken.

Now investigating per svivian

**Comment by fulldecent** [comment] 2016-01-07 22:40
The string for https://heroanswers.org/142/ is:

 > string(5) "/142/" 

And for https://heroanswers.org/142/can-wife-receive-benefits-after-pass-and-100%25-unemployable?show=142#q142 is:

> string(74) "/142/can-wife-receive-benefits-after-pass-and-100%25-unemployable?show=142"

**Comment by svivian** [comment] 2016-01-28 17:31
I think this must be a server issue. I've tried multiple set ups and have not been able to reproduce the issue, and can't see any reason why it would cause a 404 when adding `%25` to the URL. So unfortunately I have no way to fix this, unless you're able to figure out the issue yourself.

A few things you might want to check:

- Remove all plugins and see if the problem persists.
- Change the theme to one of the other Q2A defaults.
- Try a different URL format in Admin>General.
- Double-check everything in your htaccess is correct.
- Try some other flags in the RewriteRule (for example the [NE](https://httpd.apache.org/docs/2.2/rewrite/flags.html#flag_ne) flag or B flag may help).

I'm closing this for now, but if you discover the cause do let me know, and if there is some change I can make to Q2A to accommodate this, I will. Thanks.

**Closed by svivian** 2016-01-28 17:31 UTC
