### ISSUE TITLE
use multibyte functions

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#383] opened 2016-02-11 12:33 UTC
Some codeparts use strlen instead of mb_strlen, which might cause some issues under some circumstances (especially when people use unicode characters in texts and so on).

http://wpengineer.com/2410/dont-use-strlen/
http://php.net/manual/en/ref.mbstring.php
http://php.net/manual/en/mbstring.overload.php

Would have to inspect where it might cause problems, but mb_ should be safe to use (with the UTF-8 encoding).

**Comment by svivian** [comment] 2016-02-11 12:50
Funny enough I mentioned this to Gideon (the original developer) a while back. The places where we use `strlen` are not to actually check the length, but check that a string is set (i.e. 0 characters vs >0 characters). I believe it was for performance reasons, though using `empty` would serve the same purpose AFAIK.

If you spot any instances where `strlen` is used for the actual length of the string let me know, those ones _should_ be replaced with `qa_strlen`.

**Comment by DanielRuf** [comment] 2016-02-11 13:06
`empty` could be problematic in some cases

> The following things are considered to be empty:
> 
>  "" (an empty string)
> 0 (0 as an integer)
v0.0 (0 as a float)
> "0" (0 as a string)
> NULL
> FALSE
> array() (an empty array)
> $var; (a variable declared, but without a value)

> If you spot any instances where strlen is used for the actual length of the string let me know, those ones should be replaced with qa_strlen.

Ok.

**Comment by svivian** [comment] 2016-02-26 14:01
Going to close this for now. If you find any specific problems, please let me know or file a PR. Thanks.

**Comment by DanielRuf** [comment] 2016-02-26 14:36
Found one issue related to private messages, but may be someother issue, not directly related to this.

When sending a private message with the text `电脑坏了。` we get `A server error occurred - please try again.` but the message is sent. Sending normal test (eg 123 123) does not produce this.

In admin/layout the string gets removed after submission (box content in right sidebar).

**Comment by DanielRuf** [comment] 2016-03-17 19:22
@svivian not that you oversaw the last comment. Will test this also on 1.8.

Can you reproduce this?

**Comment by DanielRuf** [comment] 2016-03-18 08:54
It seems this is fixed in 1.7.4 and 1.8 as I can not reproduce it anymore on the current [Q2A Demo Sandbox](http://demo.question2answer.org/) and locally with a fresh 1.8 version

**Comment by svivian** [comment] 2016-03-20 00:21
I am not able to reproduce this issue either. Closing.

**Closed by svivian** 2016-03-20 00:21 UTC
