### ISSUE TITLE
hentry issue

### ISSUE THREAD

**Issue by rinkublog** [q2a/question2answer#286] opened 2015-08-24 11:34 UTC
You define hentry class after H1(main headline) please fix it and also remove multiple entry-title.

**Comment by svivian** [comment] 2015-08-24 15:52
Hi, thanks for the report. Please can you be more specific about what the problem is? `hentry` is used on each "content block" like question, answer, comment so I think everything is valid.

However, from Q2A 1.8 we are removing this in favour of the proper schema.org microdata, so it's likely this won't be fixed.

**Comment by rinkublog** [comment] 2015-08-25 04:16
When i test page in Google structure data then i found entry-title is name of user instead main headline. Yes you can use multiple hentry but hentry has not defined before main headline so Google can't find what is headline of page. Please make it more SEO friendly. Because SEO is everything of a website.

**Comment by svivian** [comment] 2015-08-25 11:40
Yes that was really just a quick fix for the posts not having an `entry-title` before. As I said Q2A 1.8 replaces this with better microdata so it's not worth fixing this now, sorry.

**Closed by svivian** 2015-08-25 11:40 UTC

**Comment by yerbol89** [comment] 2015-08-25 12:42
@svivian you can tell the approximate date of release 1.8? Thanks.

**Comment by svivian** [comment] 2015-08-26 12:29
@yerbol89 aiming for before the end of the year, but it depends on how much I get done, of course.
