### ISSUE TITLE
[Bug] Extra fields on user pages or registration form not able to set First

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#509] opened 2017-03-24 05:54 UTC
I added Extra fields on user pages or registration form but not able to set it as first. This is working perfectly fine with v1.7.3. It is issue with latest code from Github v1.8

try admin->Users->Add new field and set it as first.

<img width="517" alt="screen shot 2017-03-23 at 10 49 07 pm" src="https://cloud.githubusercontent.com/assets/6511264/24317827/4f7bab7c-10b9-11e7-829f-e9bd80013c1e.png">

**Comment by ProThoughts** [comment] 2017-04-09 03:54
This issue is still seen with latest github v1.8. Checked today.

**Comment by svivian** [comment] 2017-04-12 11:03
I cannot reproduce this. When I select First, it goes first. What are you setting as "Content type" and "Visible for"?

**Comment by ProThoughts** [comment] 2017-04-12 15:46
I selected Content type:  Linked url/single line text/multiple line of text, select anything. For Visible for: anybody.  Position:  first. Try on latest q2a version at  http://demo18.question2answer.info

I will check qa_userfields table and update you.

**Comment by svivian** [comment] 2017-04-12 23:46
Yes I can reproduce on that site. I think something is probably messed up with the position numbering.

**Comment by svivian** [comment] 2017-07-10 23:49
Any update? Can you post the content of your qa_userfields table? I think it will show the positions are not in order. But I never found anything in Q2A that messes them up.

**Comment by ProThoughts** [comment] 2017-07-11 05:35
Please see qa_userfields table, looks like position numbering issue. It is not setting to 0.
<img width="631" alt="screen shot 2017-07-10 at 10 31 34 pm" src="https://user-images.githubusercontent.com/6511264/28052394-c84db1e8-65bf-11e7-9901-b7f2d7c62db9.png">

**Comment by svivian** [comment] 2017-07-11 09:46
Yes the problem is that `name` has position 0. When you set something else to "First" it goes to position 1 and reorders everything else. If you set `name` to 5, then reorder through Q2A it will work as expected.

But now the issue is, how did it get position 0 in the first place? I've tried various things but could not get it to do that.

**Comment by svivian** [comment] 2017-07-11 10:32
OK found the issue, the part that creates the initial fields was setting the first field to position 0. Now fixed.

You'll still have to fix your userfields table manually. But the bug was only introduced a few months ago in the 1.8 branch (5f9c2b85020b161bc62406c4979e54268b0c24bc) so shouldn't affect many people.

**Closed by svivian** 2017-07-11 10:32 UTC
