### ISSUE TITLE
Bug saving numbered lists

### ISSUE THREAD

**Issue by pchamo** [q2a/question2answer#470] opened 2016-11-23 17:07 UTC
I'm using numbered lists, but I need to insert some text outside the numbered list, like this:

    1. One
    2. Two
    3. Three

Blah... blah...

     4. Four
     5. Five

More blah... blah...

      6. Six

But at saving time, Question2Answers changes the edited texts, breaking the WYSIWYG, giving this result:

    1. One
    2. Two
    3. Three

Blah... blah...

     1. Four
     2. Five

More blah... blah...

      1. Six

So, I'm afraid it's not possible to get that kind of numbered lists! I'm using the option "properties of numbered lists" to change the initial value of the numbered lists, but at saving time those values are reset to "1".

**Comment by pupi1985** [comment] 2016-11-23 19:17
The issue is based on the fact that current stable version of htmlLawed does not support HTML5. The funny thing is that the `start` attribute of the `ol` was deprecated in HTML4 and got un-deprecated in HTML5. So, for htmlLawed it is deprecated.

HtmlLawed allows enabling deprecated attributes but that will enable all. It also allows to set key-value pairs that enable/disable specific element-attribute pairs (which is called `spec`). The thing is that the setting that controls if the deprecated attributes are allowed or not, ridiculously, has precedence over the `spec`. So if you want to enable a deprecated attribute you have to enable all attributes and disable all but the `ol=start`. Hopefully I'm wrong and missed something.

So the approaches I can think of to tackle this would be:
- Set the value in the `spec` along with all deprecated elements and attributes (the same as before)
- Upgrade to the beta version of htmLawed which supports HTML5 and the attribute is no longer deprecated there
- Hack the library removing the deprecation (argh!). This can be done by removing the second `'start'=>array('ol'=>1),`
- Delaying the fix up to the next release (either 1.8 or 1.7.5). By that time htmLawed might have released a stable version and this would get fixed with the new library automatically.

I'd go for the last one as the htmLawed maintainer mentioned he expected to release a final version some time in 2016. Even if it is delayed, I guess the timing should be similar or even earlier than the Q2A release.

**Comment by pchamo** [comment] 2016-11-25 00:07
Thank you for the info. I have no hurry and can wait until the next Q2A release. Best regards. Pablo Chamorro

**Comment by svivian** [comment] 2017-03-11 16:11
htmLawed 1.2 was released a few weeks ago that fixes this. Will be included in Q2A 1.8.

**Closed by svivian** 2017-03-11 16:11 UTC
